### PR TITLE
Add notice for the DConf hackathon

### PR DESCRIPTION
**Pull request by wilzbach**
Sorry that I am late to the party.

I will hopefully be able to extend this text soon.

### CODE REVIEW

**Comment by wilzbach** [comment]
Ping @andralex - we are already quite late with putting this information online. Any chance we could get this "deployed"? :)

**Comment by andralex** [comment]
done

**Comment by wilzbach** [comment]
Thanks a lot! Should we remove the "Call for Submissions" block?

**Comment by andralex** [comment]
affirmative

**Comment by wilzbach** [comment]
> affirmative

https://github.com/dlang/dconf.org/pull/149

**Pull request merged**
