### PR TITLE
Move DConf 2016 to past tense.

### PR DESCRIPTION
**Pull request by smandy**
DConf now concluded so the dconf 2016 references should be moved to past tense.

### CODE REVIEW

**Comment by wilzbach** [comment]
hey guys, someone with merge rights listening?
DConf was three months ago, so we should really move it to the past ;-)

**Comment by wilzbach** [comment]
> DConf was three months ago, so we should really move it to the past ;-)

Yet another week - friendly ping ;-)

**Comment by yebblies** [comment]
I would merge it, but IIRC only @andralex can actually push to the site.

**Comment by wilzbach** [comment]
> I would merge it, but IIRC only @andralex can actually push to the site.

I pinged a couple of people via mail and there seems to be light at the the end of the tunnel (just kidding) - I do have some good news:

1) It's possible to add dconf.org to Digger and thus DAutoTest and it's auto deployment
2) @CyberShadow now has the correct permissions, s.t. auto-deployment can work
3) @CyberShadow is a bit busy atm, so I will do my best to help him there (unfortunately my time is also limited), but I hope at some point next week we should have auto-merge for dconf.org (no promise though)

**Comment by smandy** [comment]
@andralex  Pls merge this !!!!

**Comment by smandy** [comment]
@CyberShadow Pls merge this!!!

**Comment by andralex** [comment]
Ah, quite timely seeing as we'll send the Call for Submissions for DConf 2017 soon. Thanks!

**Comment by andralex** [comment]
@CyberShadow do we have automatic update of this?

**Comment by wilzbach** [comment]
> do we have automatic update of this?

Unfortunately not :/

**Pull request merged**
