### PR TITLE
Add video links

### PR DESCRIPTION
**Pull request by schveiguy**
Not 100% sure that this is how it works, but from reading the macros, I think this is it.

### CODE REVIEW

**Comment by WalterBright** [comment]
Can you update http://wiki.dlang.org/Videos too, please?

**Comment by schveiguy** [comment]
Did I do this right, or has the website just not been rebuilt?

**Comment by wilzbach** [comment]
> Did I do this right, or has the website just not been rebuilt?

I think someone needs to manually deploy it - maybe @CyberShadow knows more?

**Comment by wilzbach** [comment]
Ping guys, has no one here deploy/merge rights?

**Comment by CyberShadow** [comment]
> I think someone needs to manually deploy it - maybe @CyberShadow knows more?

Andrei asked Jan to give me dconf.org rights in April. Nothing happened...

**Comment by wilzbach** [comment]
> @CyberShadow: Well, if you want to host everything, I can always let you take over the DNS zone. ;P

I am pretty sure he doesn't want too ;-)
Btw see [my comment](https://github.com/dlang/dconf.org/pull/138#issuecomment-238092778) at the other open issue. This problem is being worked on and dconf.org will get auto-deploy .

**Pull request merged**
