### PR TITLE
[2018] Add keynote speakers

### PR DESCRIPTION
**Pull request by mdparker**

### CODE REVIEW

**Comment by wilzbach** [comment]
image

I resized the images for you and put them in the `images` directory.
I also think that you accidentally swapped Content and Keynote speakers

Preview:

image

**Comment by mdparker** [comment]
No, I left the Keynote Speakers header out intentionally. But I had intended to put the pictures right below the paragraph announcing Martin's participation.

**Comment by wilzbach** [comment]
Ah. Simply drop my commit then. Sorry. I just wanted to speed up things.

**Comment by mdparker** [comment]
No, that's fine, I'll fix it.

**Comment by mdparker** [comment]
I also fixed the early-bird discount. That's rather important.

**Comment by mdparker** [comment]
@wilzbach Also, could you do me a favor? As soon as this is merged, can you share the new blog announcement to reddit and post it in the forums? I'm running late for work.

https://dlang.org/blog/2018/01/31/dconf-2018-register-now/

**Comment by wilzbach** [comment]
Sure thing - can I merge https://github.com/dlang/dconf.org/pull/225 too?

**Comment by mdparker** [comment]
Sure

**Comment by wilzbach** [comment]
Done:

https://forum.dlang.org/post/dkxglfqsziqcprlczqcw@forum.dlang.org
https://www.reddit.com/r/programming/comments/7udoi2/registration_for_dconf_2018_is_now_open

**Pull request merged**
