### PR TITLE
Add timezone to deadline dates

### PR DESCRIPTION
**Pull request by mdparker**

### CODE REVIEW

**Comment by wilzbach** [comment]
Mike, please feel free to merge such simple stuff immediately. Especially if it's so time sensitive.

**Comment by mdparker** [comment]
I don't believe I have merge rights.

**Comment by wilzbach** [comment]
GitHub says you do - both of us are marked as members...
Did you try?

**Comment by mdparker** [comment]
No, I didn't. But in the dlang organization, I'm only a member of Team DIP. Next time I make a PR here, I'll see if the merge button shows up.

**Comment by mdparker** [comment]
https://github.com/orgs/dlang/teams/dconf-org/members

**Comment by wilzbach** [comment]
Oh. Sorry, but I can't add you to the team. Only @andralex can...

**Comment by andralex** [comment]
Added.

**Pull request merged**
