### PR TITLE
Fix header + footer

### PR DESCRIPTION
**Pull request by wilzbach**
The DConf page is deeply in need of some love. This is a first step on a long road.

Header
----------

Before:

image

After:

image

Footer
---------

Before:

image

After:

image

CC @andralex

### CODE REVIEW

**Comment by andralex** [comment]
This has broken the website: http://dconf.org/2017/index.html

**Comment by wilzbach** [comment]
> This has broken the website: http://dconf.org/2017/index.html

I can't reproduce this locally? How do you build the website?
I simply ran `make` ...

**Comment by wilzbach** [comment]
>  I can't reproduce this locally? How do you build the website?

For reference, I just dumped my local build:

http://files.wilzba.ch/dlang/dconf.org/2017/

**Comment by andralex** [comment]
I just issue `make clean && make`. For some reason `out/2017/images/dconf_logo_2017.svg` appears as a directory, not file.

**Comment by wilzbach** [comment]
> I just issue make clean && make. For some reason out/2017/images/dconf_logo_2017.svg appears as a directory, not file.

That's really weird. However, currently a lot more weirdness seems to be going on:

image

**Comment by andralex** [comment]
There's a bunch of `mkdir`s that have no business being there. Look at the end of the make run log:

```
mkdir -p ../out/2017/images
mkdir -p ../out/2017/images/heimathafen.png
mkdir -p ../out/2017/images/dconf_logo_2017.svg
mkdir -p ../out/2017/includes
mkdir -p ../out/2017/includes/style.css
```

**Comment by wilzbach** [comment]
> There's a bunch of mkdirs that have no business being there. Look at the end of the make run log:

I didn't even touch the Makefile :O 
Though it still looks good on my end:

```
make[1]: Entering directory '/home/xsebi/projects/dlang/dconf.org/2017'
dmd -c -o- -Df../out/2017/contact.html macros.ddoc contact.dd
dmd -c -o- -Df../out/2017/index.html macros.ddoc index.dd
dmd -c -o- -Df../out/2017/registration.html macros.ddoc registration.dd
dmd -c -o- -Df../out/2017/schedule/index.html macros.ddoc schedule/index.dd
dmd -c -o- -Df../out/2017/speakers/index.html macros.ddoc speakers/index.dd
dmd -c -o- -Df../out/2017/thankyou.html macros.ddoc thankyou.dd
dmd -c -o- -Df../out/2017/venue.html macros.ddoc venue.dd
mkdir -p ../out/2017/images/
cp images/heimathafen.png ../out/2017/images/heimathafen.png
cp images/dconf_logo_2017.svg ../out/2017/images/dconf_logo_2017.svg
mkdir -p ../out/2017/includes/
cp includes/style.css ../out/2017/includes/style.css
make[1]: Leaving directory '/home/xsebi/projects/dlang/dconf.org/2017'
```

**Comment by andralex** [comment]
For whatever reasons the culprit is `make` on OSX. Works fine on Linux, where I rebuilt and deployed.

**Pull request merged**
