### PR TITLE
Add encrypted SSH deployment key

### PR DESCRIPTION
**Pull request by wilzbach**
This should now complete the auto-deploy setup :)

Thanks a lot to @CyberShadow for encrypting the ssh key!

### CODE REVIEW

**Comment by CyberShadow** [comment]
@wilzbach OK, merge this whenever you have the time to troubleshoot anything that might go wrong due to merging this :)

**Comment by wilzbach** [comment]
> OK, merge this whenever you have the time to troubleshoot anything that might go wrong due to merging this :)

I don't have merge rights here, but would have time to troubleshoot atm ;-)

Could you please merge this and https://github.com/dlang/dconf.org/pull/152 to check whether it's working?

**Comment by CyberShadow** [comment]
Doesn't look like it. Permission errors.

**Comment by wilzbach** [comment]
Okay the good news: seems like `make`, the SSH login via the encrypted worked, but `rsync` complains about permission errors:

```
rsync: mkstemp "/usr/local/www/dconf.org/data/2016/talks/.schadek.pdf.DRIzXE" failed: Permission denied (13)
rsync: mkstemp "/usr/local/www/dconf.org/data/2016/talks/.schveighoffer.html.6eBRkx" failed: Permission denied (13)
rsync: mkstemp "/usr/local/www/dconf.org/data/2016/talks/.schveighoffer.pdf.mkIThZ" failed: Permission denied (13)
rsync: mkstemp "/usr/local/www/dconf.org/data/2016/talks/.sechet.html.nElOmz" failed: Permission denied (13)
rsync: mkstemp "/usr/local/www/dconf.org/data/2016/talks/.sechet.pptx.mi9ohY" failed: Permission denied (13)
rsync: mkstemp "/usr/local/www/dconf.org/data/2016/talks/.smith.html.aettwf" failed: Permission denied (13)
rsync: mkstemp "/usr/local/www/dconf.org/data/2016/talks/.smith.pdf.vLbqXa" failed: Permission denied (13)
rsync: mkstemp "/usr/local/www/dconf.org/data/2016/talks/.thaut.html.zsAwqI" failed: Permission denied (13)
rsync: mkstemp "/usr/local/www/dconf.org/data/2016/talks/.thaut.pdf.y4uFm9" failed: Permission denied (13)
rsync: mkstemp "/usr/local/www/dconf.org/data/2016/talks/.watson.html.PeXZbq" failed: Permission denied (13)
rsync: mkstemp "/usr/local/www/dconf.org/data/2016/talks/.watson.pptx.0aSgTo" failed: Permission denied (13)
rsync: mkstemp "/usr/local/www/dconf.org/data/2016/talks/.zvibel.html.nINv41" failed: Permission denied (13)
rsync: mkstemp "/usr/local/www/dconf.org/data/2016/talks/.zvibel.pdf.0Strwb" failed: Permission denied (13)
rsync: mkstemp "/usr/local/www/dconf.org/data/2017/.contact.html.KdOHZw" failed: Permission denied (13)
rsync: mkstemp "/usr/local/www/dconf.org/data/2017/.index.html.7Uca8i" failed: Permission denied (13)
rsync: mkstemp "/usr/local/www/dconf.org/data/2017/.registration.html.KKaLOk" failed: Permission denied (13)
rsync: mkstemp "/usr/local/www/dconf.org/data/2017/.thankyou.html.9kEHyL" failed: Permission denied (13)
rsync: mkstemp "/usr/local/www/dconf.org/data/2017/.venue.html.L1vRYM" failed: Permission denied (13)
rsync: mkstemp "/usr/local/www/dconf.org/data/2017/schedule/.index.html.L6P0mc" failed: Permission denied (13)
rsync: mkstemp "/usr/local/www/dconf.org/data/2017/speakers/.index.html.IbCyyf" failed: Permission denied (13)
``

```
> ls -l 2017
-rw-r--r--  1 dconf.org  dconf.org  3920 Mar  3 17:56 contact.html
drwxr-xr-x  2 dconf.org  dconf.org     4 Mar  3 17:56 images
drwxr-xr-x  2 dconf.org  dconf.org     3 Mar  3 17:56 includes
-rw-r--r--  1 dconf.org  dconf.org  6487 Mar  3 17:56 index.html
-rw-r--r--  1 dconf.org  dconf.org  7155 Mar  3 17:56 registration.html
drwxr-xr-x  2 dconf.org  dconf.org     3 Mar  3 17:56 schedule
drwxr-xr-x  2 dconf.org  dconf.org     3 Mar  3 17:56 speakers
-rw-r--r--  1 dconf.org  dconf.org  3698 Mar  3 17:56 thankyou.html
-rw-r--r--  1 dconf.org  dconf.org  4615 Mar  3 17:56 venue.html
```

How about a `chmod -R g+w`?

**Pull request merged**
