### PR TITLE
Fix a few typos

### PR DESCRIPTION
**Pull request by wilzbach**

### CODE REVIEW

**Comment by dcarp** [comment]
Also, the discount and the early-bird fee do not sum up.

**Comment by wilzbach** [comment]
Yeah I wanted to add @mdparker about that. (that's why I originally made the PR, but somehow forgot about it the most important bit).

**Comment by mdparker** [comment]
That's supposed to be 15% early bird fee!

**Comment by wilzbach** [comment]
> That's supposed to be 15% early bird fee!

Ok. Changed.
BTW for a recent conference I joined, they had an interesting strategy: every week or so they bumped the price for ~5-15€ and made a big fuzz about it (a la "catch your ticket while it's still cheap"). They sold more than 1600 seats for a shitty conference.

**Comment by wilzbach** [comment]
As I saw that the blog post is out (https://dlang.org/blog/2018/01/31/dconf-2018-register-now/), I'm going to merge this as it fixes a critical typo.

**Comment by dcarp** [comment]
@mdparker The venue link in the blog has a typo:
```
- http://dconf.org/2018/venue.htm
+ http://dconf.org/2018/venue.html
```

**Pull request merged**
